services:
  backend:
    build: ./cloud_backend
    container_name: cloud_backend
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password

  frontend:
    build: ./cloud_frontend
    container_name: cloud_frontend
    ports:
      - "5173:5173"
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8080/